/*
 * GeneratedClass - Represents a complete generated Java source file
 * Author: Sekacorn
 * Created from scratch; no third-party code copied.
 */
package com.sekacorn.corn.codegen;

import java.util.Set;
import java.util.TreeSet;

public final class GeneratedClass {
    private final String packageName;
    private final String className;
    private final Set<String> imports;
    private final Set<String> classFields;
    private final String classBody;
    private final String originalProgramId;

    public GeneratedClass(String packageName, String className, Set<String> imports,
                          Set<String> classFields, String classBody, String originalProgramId) {
        this.packageName = packageName;
        this.className = className;
        this.imports = new TreeSet<>(imports);
        this.classFields = new TreeSet<>(classFields);
        this.classBody = classBody;
        this.originalProgramId = originalProgramId;
    }

    public String render() {
        StringBuilder sb = new StringBuilder();
        sb.append("/*\n");
        sb.append(" * Generated from COBOL program: ").append(originalProgramId).append("\n");
        sb.append(" * Generated by Corn COBOL-to-Java Compiler\n");
        sb.append(" */\n");
        sb.append("package ").append(packageName).append(";\n\n");

        for (String imp : imports) {
            sb.append("import ").append(imp).append(";\n");
        }
        if (!imports.isEmpty()) sb.append("\n");

        sb.append("public class ").append(className).append(" {\n\n");
        for (String field : classFields) {
            sb.append("    ").append(field).append("\n");
        }
        if (!classFields.isEmpty()) sb.append("\n");
        sb.append(classBody);
        sb.append("}\n");
        return sb.toString();
    }

    public String getPackageName() { return packageName; }
    public String getClassName() { return className; }
    public Set<String> getImports() { return Set.copyOf(imports); }
    public String getClassBody() { return classBody; }
    public String getOriginalProgramId() { return originalProgramId; }

    public String getFileName() {
        return className + ".java";
    }

    public String getRelativePath() {
        return packageName.replace('.', '/') + "/" + getFileName();
    }
}
